language: android
jdk:
    - oraclejdk8
android:
    components:
        - tools
        - build-tools-25.0.0
        - platform-tools
        - android-23
script:
   - cd app
   - chmod +x ./gradlew
   - ./gradlew clean assembleDebug
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'